In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2


# **Задание 1**


In [6]:
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)

print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.51073929 0.40460123 0.92499894 ... 0.10379026 0.58333093 0.36967066]
 [0.19226877 0.9821013  0.3496574  ... 0.36649611 0.76707511 0.52089618]
 [0.78332339 0.49527716 0.12813992 ... 0.364803   0.77972606 0.10878695]
 ...
 [0.11072161 0.18673333 0.1914293  ... 0.61298226 0.5119094  0.89706022]
 [0.47533947 0.1909584  0.73722861 ... 0.39908961 0.81193722 0.60952264]
 [0.25852121 0.94302715 0.30575729 ... 0.34171187 0.91625983 0.86333722]]
[[0.83907349 0.40577186 0.79394075 ... 0.71021667 0.26360142 0.48111941]
 [0.17728159 0.36017439 0.07627097 ... 0.61948193 0.96418486 0.29621783]
 [0.8800964  0.63499358 0.85383132 ... 0.06318749 0.93291072 0.01413686]
 ...
 [0.41895607 0.72140654 0.50670655 ... 0.43378878 0.04258303 0.26473393]
 [0.92468449 0.51615154 0.69821543 ... 0.61425175 0.07148152 0.90428119]
 [0.95597762 0.37709314 0.68899951 ... 0.63390729 0.84982824 0.14047245]]


In [7]:
def mult(a, b):
    n = len(a)
    result = [[0] * n for _ in range(n)]

    for i in range(n):
        for j in range(n):
            for k in range(n):
                result[i][j] += a[i][k] * b[k][j]
    return result

In [8]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result


In [9]:
%%time
M1 = mult(a, b)

CPU times: user 690 ms, sys: 1.56 ms, total: 691 ms
Wall time: 697 ms


In [10]:
%%time
M2 = np_mult(a, b)

CPU times: user 2.52 ms, sys: 3.28 ms, total: 5.8 ms
Wall time: 8.77 ms


In [11]:
np.abs(np.array(M1) - M2).sum()

1.495692458775011e-11

# **Задание 2**

In [12]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.53566413 0.44447892 0.01350484] [0.75112863 0.44137682 0.88354933]


In [13]:
def scalar_product(a,b):
    s = 0
    s = sum([a[i]*b[i] for i in range(len(a))])
    return s

In [14]:
def np_scalar_product(a,b):
    s = 0
    s = np.dot(a, b)
    return s

In [15]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
np.abs(product_1 - product_2).sum()

CPU times: user 25 µs, sys: 0 ns, total: 25 µs
Wall time: 27.9 µs
CPU times: user 144 µs, sys: 0 ns, total: 144 µs
Wall time: 578 µs


0.0

Почему методы numpy оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:**

1)У numpy есть преимущество локальности ссылок, так как в нем используются упакованные массивы однородного типа, а в Python списки представляют собой массивы указателей на объекты, даже если они все однотипные.

2)numpy в большинтсве своем реализован на языке C, что позволяет избежать общих затрат на циклы в Python, косвенное обращение с указателями и проверку динамического типа для каждого элемента.

# **Задание 3**

In [16]:
def np_diag_2k(a):
  arr = np.array(a)
  n = arr.shape[0]
  res = 0

  for i in range(n):
      if arr[i, i] % 2 == 0:
          res += arr[i, i]
  return res

In [17]:
a = np.random.randint(1, 10, size=(5, 5))
a

array([[7, 8, 4, 1, 3],
       [6, 5, 3, 8, 8],
       [8, 1, 1, 9, 8],
       [8, 5, 2, 9, 3],
       [4, 5, 2, 5, 6]])

In [18]:
%%time
np_diag_2k(a)

CPU times: user 102 µs, sys: 0 ns, total: 102 µs
Wall time: 86.3 µs


6

# **Задание 4**

In [19]:
def np_sec_av(*A):
    result = np.cumsum(A, axis=1)
    return result

In [20]:
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[8.90010490e-01 7.18863987e-01 5.51224232e-02 8.77010349e-01
 7.92015440e-01 2.00556655e-01 9.77286334e-01 5.17371506e-01
 1.43941433e-01 1.93839685e-01 6.88009445e-01 7.45492174e-01
 6.10569826e-01 6.19902196e-01 3.92944047e-01 1.53089759e-01
 6.64701223e-02 6.63146673e-01 1.76043744e-01 9.29847797e-01
 2.47186069e-01 2.01448968e-01 4.52170910e-01 2.78557819e-01
 8.84486506e-01 9.90674176e-01 2.51856296e-01 5.73998418e-03
 4.74114597e-01 5.79772887e-01 8.17201938e-01 7.26161849e-01
 7.13744661e-02 6.24941945e-02 7.88714413e-01 4.55070485e-01
 1.27433303e-01 9.33933170e-01 1.01070852e-01 3.97181908e-01
 4.04210539e-01 2.76967811e-01 9.86590354e-01 7.87125155e-01
 3.31268620e-01 1.84140942e-01 2.05070677e-01 7.41044957e-01
 1.33603623e-01 2.99973997e-01 4.72099393e-01 4.06317444e-02
 2.66447141e-01 1.57413778e-01 2.25380853e-01 7.24604383e-01
 9.37562518e-01 5.71648120e-01 4.24750155e-01 8.63898508e-01
 8.26776334e-01 3.37375065e-01 3.89762138e-01 9.40698821e-01
 4.72340708e-02 1.619713

# **Задание 5**

In [22]:
def np_encode(a):
    elements = []
    counts = []

    current_element = a[0]
    current_count = 1

    for i in range(1, len(a)):
        if a[i] == current_element:
            current_count += 1
        else:
            elements.append(current_element)
            counts.append(current_count)
            current_element = a[i]
            current_count = 1

    elements.append(current_element)
    counts.append(current_count)

    result = np.array(elements), np.array(counts)
    return result

In [23]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 36 µs, sys: 6 µs, total: 42 µs
Wall time: 44.8 µs


# **Задание 6**

In [35]:
from copy import copy

def np_transformation(X, a):
    """
    param X: array
    """
    x_copy = np.copy(X)

    x_copy[1::2] = a
    x_copy[::2] = np.power(x_copy[::2], 3)

    new_array = np.concatenate((X, x_copy[::-1]))
    result = new_array[::-1]

    return result

In [36]:
X = np.array([i for i in range(1, 10, 2)])
%time S2 = np_transformation(X, 5)

CPU times: user 100 µs, sys: 0 ns, total: 100 µs
Wall time: 104 µs
